### ISSUE TITLE
Timeout increase

### ISSUE THREAD

**Issue by drptbl** [yovanoc/mailsac#11]
Timeout is hardcoded to 3 seconds which is quite low, especially when you're connecting to mailsac API through VPN.

Is there any way to increase it easy way without forking the project and editing hardcoded value?

Thanks,
Jakub.

cc @yovanoc

**Comment by yovanoc** [comment]
Actually not but I could do that

**Comment by drptbl** [comment]
@yovanoc would be awesome, thank you! 🎉

**Comment by yovanoc** [comment]
Available right now on NPM. This is the second argument to the constructor of the Client class :)
