### ISSUE TITLE
Latest version 0.0.9 does not include the axios upgrade

### ISSUE THREAD

**Issue by joaguirrem** [yovanoc/mailsac#19]
The PR: https://github.com/yovanoc/mailsac/pull/16 was merged on Apr. 22 but a new version of the dependency was not deployed yet.

[Server-Side Request Forgery](https://www.npmjs.com/advisories/1594)

Overview
The `axios` NPM package before 0.21.1 contains a Server-Side Request Forgery (SSRF) vulnerability where an attacker is able to bypass a proxy by providing a URL that responds with a redirect to a restricted host or IP address.

**Comment by yovanoc** [comment]
I'm currently doing some cleaning on the repo, I will publish this soon, sorry for the delay

**Comment by yovanoc** [comment]
I've done my cleaning, and push it to npm too :)
